///////////////////////////////////////////////////////////
//  Sistema.cs
//  Implementation of the Class Sistema
//  Generated by Enterprise Architect
//  Created on:      05-Jul-2007 09:07:07
///////////////////////////////////////////////////////////

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using NHibernate;
using Iesi.Collections;
using Fil.Modelo.Entidades;

namespace Fil.Modelo.Entidades {

	public abstract class Sistema 
  {

#region Campos Privados

    private static Usuario usuarioActual;
    private const string USUARIO_SISTEMA_NOMBRE = "";
    private const string USUARIO_SISTEMA_PASSWORD = "";
    
#endregion

#region Propiedades

    /// <summary>
    /// Usuario logueado actualmente en el sistema
    /// </summary>
    public static Usuario UsuarioActual
    {
      get
      {
        return usuarioActual;
      }
      set
      {
        usuarioActual = value;
      }
    }
    
#endregion

#region "Metodos"

    public static bool IngresarUsuario(string username, string pass)
    {
      username = username.Trim();
      pass = pass.Trim();

      Usuario usr;

      //Agergo un harcode para tener un usuario y pass que pase siempre
      //User: (vacio)
      //Pass: (vacio)
      if (username.ToLower() == USUARIO_SISTEMA_NOMBRE && pass == USUARIO_SISTEMA_PASSWORD )
      {
        usr = new Usuario(USUARIO_SISTEMA_NOMBRE, "XX", "XX", USUARIO_SISTEMA_PASSWORD);
        usuarioActual = usr;
        return true;
      }

      usr = Helpers.UsuarioHelper.ObtenerPorUsername(username);
      if (usr != null)
      {
        if (usr.Password == pass)
        {
          UsuarioActual = usr;
          return true;
        }
      }
      return false;
    }

#endregion

  }//end Sistema

}//end namespace Entidades