///////////////////////////////////////////////////////////
//  Sistema.cs
//  Implementation of the Class Sistema
//  Generated by Enterprise Architect
//  Created on:      05-Jul-2007 09:07:07
///////////////////////////////////////////////////////////

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using NHibernate;
using Iesi.Collections;
using Fil.Modelo.Entidades;

namespace Fil.Modelo.Entidades {

	public class Sistema 
  {

#region Campos Privados

    private Usuario usuarioActual;
    
#endregion

#region Constructores

    /// <summary>
    /// Constructor sin parámetros necesario para NHibernate
    /// </summary>
    protected Sistema()
    {
    }
    
#endregion

#region Propiedades

    /// <summary>
    /// Usuario logueado actualmente en el sistema
    /// </summary>
    public Usuario UsuarioActual
    {
      get
      {
        return usuarioActual;
      }
      set
      {
        usuarioActual = value;
      }
    }
    
#endregion

	}//end Sistema

}//end namespace Entidades