///////////////////////////////////////////////////////////
//  UnidadDeGestion.cs
//  Implementation of the Class UnidadDeGestion
//  Generated by Enterprise Architect
//  Created on:      05-Jul-2007 09:07:07
///////////////////////////////////////////////////////////

using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using NHibernate;
using Iesi.Collections;
using Fil.Modelo.Helpers;

namespace Fil.Modelo.Entidades {

  /// <summary>
  /// Representa una unidad de gestion operativa
  /// </summary>
	public class UnidadDeGestion: IEntidadPersistible
  {

#region Campos Privados

    private string id;
    private int codigo;

#endregion

#region Constructores

    /// <summary>
    /// Constructor sin parámetros necesario para NHibernate
    /// </summary>
    public UnidadDeGestion()
    {
    }
    
#endregion

#region Propiedades

    /// <summary>
    /// Identificador del perfil
    /// </summary>
    public virtual string Id
    {
      get { return id; }
      set { id = value; }
    }

    /// <summary>
    /// Código autonumerico
    /// </summary>
    public virtual int Codigo
    {
      get { return codigo; }
      set { codigo = value; }
    }

#endregion

#region Metodos Publicos

    /// <summary>
    /// Guarda la instancia en la base de datos
    /// </summary>
    public virtual void Guardar()
    {
      if (this.id == null)
        UnidadDeGestionHelper.Guardar(this);
      else
        UnidadDeGestionHelper.Actualizar(this);
    }
    /// <summary>
    /// Elimina la instancia de la base de datos
    /// </summary>
    public virtual void Eliminar()
    {
      UnidadDeGestionHelper.Eliminar(this);
    }

    public override bool Equals(object obj)
    {
      //Primero verifico si el objeto es de tipo UnidadDeGestion o hereda de UnidadDeGestion (es necesario
      //porque nhibernate genera RuntimeTypes que heredan de las clases persistentes, para 
      //manejar la instanciacion perezosa
      if ((obj.GetType() != typeof(UnidadDeGestion)) && (obj.GetType().BaseType != typeof(UnidadDeGestion)))
        return false;
      //Si es de tipo UnidadDeGestion, verifico el Id.
      return ((UnidadDeGestion)obj).Id == this.Id;
    }
    public override string ToString()
    {
      return "Unidad De Gestion";
    }
    public override int GetHashCode()
    {
      return base.GetHashCode();
    }

#endregion

  }//end UnidadDeGestion

}//end namespace Entidades